shipping/urls.py
from django.urls import path

from .views import (
    MainView,
    СounterpartyAdd,
    СounterpartyUpdate,
    СounterpartyDelete,
    ShippingInvoiceAdd,
    ShippingInvoiceUpdate,
    ShippingInvoiceDelete,
    ShipmentAdd,
    ShipmentUpdate,
    ShipmentDelete,
)

app_name = 'shipping'

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path(
        'add-counterparty/',
        СounterpartyAdd.as_view(),
        name='add_counterparty'
    ),
    path(
        'udate-counterparty/<int:pk>/',
        СounterpartyUpdate.as_view(),
        name='update_counterparty'
    ),
    path(
        'delete_counterparty/<int:pk>/',
        СounterpartyDelete.as_view(),
        name='delete_counterparty'
    ),
    path('add-invoice/', ShippingInvoiceAdd.as_view(), name='add_invoice'),
    path(
        'udate-invoice/<int:pk>/',
        ShippingInvoiceUpdate.as_view(),
        name='update_invoice'
    ),
    path(
        'delete_invoice/<int:pk>/',
        ShippingInvoiceDelete.as_view(),
        name='delete_invoice'
    ),
    path('add-shipment/', ShipmentAdd.as_view(), name='add_shipment'),
    path(
        'udate-shipment/<int:pk>/',
        ShipmentUpdate.as_view(),
        name='update_shipment'
    ),
    path(
        'delete_shipment/<int:pk>/',
        ShipmentDelete.as_view(),
        name='delete_shipment'
    ),
]

upload/urls.py
from django.urls import path

from .views import (
    main,
    ProviderAdd,
    ProviderUpdate,
    ProviderDelete,

    UploadInvoiceAdd,
    UploadInvoiceUpdate,
    UploadInvoiceDelete,

    UploadAdd,
    UploadUpdate,
    UploadDelete,
)

app_name = 'uploading'

urlpatterns = [
    path('upload-view/', main, name='main'),
    path('add-provider/', ProviderAdd.as_view(), name='add_provider'),
    path(
        'update-provider/<int:pk>/',
        ProviderUpdate.as_view(),
        name='update_provider'
    ),
    path(
        'delete-provider/<int:pk>/',
        ProviderDelete.as_view(),
        name='delete_provider'
    ),
    path('add-invoice/', UploadInvoiceAdd.as_view(), name='add_invoice'),
    path(
        'update-invoice/<int:pk>/',
        UploadInvoiceUpdate.as_view(),
        name='update_invoice'
    ),
    path(
        'delete-invoice/<int:pk>/',
        UploadInvoiceDelete.as_view(),
        name='delete_invoice'
    ),
    path('add-upload/', UploadAdd.as_view(), name='add_upload'),
    path(
        'update-upload/<int:pk>/',
        UploadUpdate.as_view(),
        name='update_upload'
    ),
    path(
        'delete-upload/<int:pk>/',
        UploadDelete.as_view(),
        name='delete_upload'
    ),
]

warehouse/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('products.urls')),
    path('shipment/', include('shipping.urls')),
    path('upload/', include('upload.urls')),
    path('admin/', admin.site.urls),
]

shipping/models.py
from django.db import models

from products.models import Product


class Сounterparty(models.Model):
    """Модель таблицы Контрагент"""

    name = models.CharField(
        max_length=120,
        verbose_name='Название контрагента'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Контрагент'
        verbose_name_plural = 'Контрагенты'


class ShippingInvoice(models.Model):
    """Модель таблицы Накладной на выгрузку"""

    conterparty = models.ForeignKey(
        "Сounterparty",
        on_delete=models.CASCADE,
        verbose_name='Контрагент'
    )

    def __str__(self):
        return f'Накладная № {self.id}'

    class Meta:
        verbose_name = 'Накладная на выгрузку'
        verbose_name_plural = 'Накладные на выгрузку'


class Shipment(models.Model):
    """Модель таблицы Выгрузка"""

    shippingInvoice = models.ForeignKey(
        "ShippingInvoice",
        on_delete=models.CASCADE,
        verbose_name='Накладная'
    )
    product = models.OneToOneField(
        Product,
        on_delete=models.CASCADE,
        verbose_name='Товар'
    )

    def __str__(self):
        return f'Выгрузка {self.product.name} \
            по накладной № {self.shippingInvoice.id}'

    class Meta:
        verbose_name = 'Выгрузка'
        verbose_name_plural = 'Выгрузки'

shipping/forms.py
from django import forms

from .models import Сounterparty, ShippingInvoice, Shipment


class СounterpartyForm(forms.ModelForm):
    class Meta(object):
        model = Сounterparty
        exclude = ()


class ShippingInvoiceForm(forms.ModelForm):
    class Meta(object):
        model = ShippingInvoice
        exclude = ()


class ShipmentForm(forms.ModelForm):
    class Meta(object):
        model = Shipment
        exclude = ()

shipping/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy

from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)
from django.views.generic.base import TemplateView

from .models import (
    Сounterparty,
    ShippingInvoice,
    Shipment
)
from .forms import (
    СounterpartyForm,
    ShippingInvoiceForm,
    ShipmentForm
)


class MainView(TemplateView):
    """Главное представление отображающее основные таблицы"""

    template_name = 'shipping/main.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["contractors"] = Сounterparty.objects.all()
        context["shippingInvoices"] = ShippingInvoice.objects.all()
        context["shipments"] = Shipment.objects.all()
        return context


class СounterpartyAdd(CreateView):
    """Добавление Контрагента"""

    form_class = СounterpartyForm
    template_name = 'form.html'
    succes_url = 'shipping:mainview'

    def form_valid(self, form):
        Сounterparty.objects.create(**form.cleaned_data)
        return redirect(self.succes_url)


class СounterpartyUpdate(UpdateView):
    """Обновление информации о Контрагенте"""

    model = Сounterparty
    template_name = 'form.html'
    success_url = reverse_lazy('shipping:mainview')
    fields = ('name',)


class СounterpartyDelete(DeleteView):
    """Удаление Контрагента"""

    model = Сounterparty
    success_url = reverse_lazy('shipping:mainview')
    template_name = 'delete.html'


class ShippingInvoiceAdd(CreateView):
    """Добавление Накладной на выгрузку"""

    form_class = ShippingInvoiceForm
    template_name = 'form.html'
    succes_url = 'shipping:mainview'

    def form_valid(self, form):
        ShippingInvoice.objects.create(**form.cleaned_data)
        return redirect(self.succes_url)


class ShippingInvoiceUpdate(UpdateView):
    """Обновление Накладной на выгрузку"""

    model = ShippingInvoice
    template_name = 'form.html'
    success_url = reverse_lazy('shipping:mainview')
    fields = ('conterparty',)


class ShippingInvoiceDelete(DeleteView):
    """Удаление Накладной на выгрузку"""

    model = ShippingInvoice
    success_url = reverse_lazy('shipping:mainview')
    template_name = 'delete.html'


class ShipmentAdd(CreateView):
    """Добавить Выгрузку"""

    form_class = ShipmentForm
    template_name = 'form.html'
    succes_url = 'shipping:mainview'

    def form_valid(self, form):
        Shipment.objects.create(**form.cleaned_data)
        return redirect(self.succes_url)


class ShipmentUpdate(UpdateView):
    """Обновить Выгрузку"""

    model = Shipment
    template_name = 'form.html'
    success_url = reverse_lazy('shipping:mainview')
    fields = ('shippingInvoice', 'product')


class ShipmentDelete(DeleteView):
    """Удалить выгрузку"""

    model = Shipment
    success_url = reverse_lazy('shipping:mainview')
    template_name = 'delete.html'

templates/shipping/main.html
{% extends "base.html" %}
{% block title %}Работа с расходами{% endblock title %}
{% block content %}

<h1>Расходы</h1>

<h3>Контрагенты</h3>
<a href="{% url "shipping:add_counterparty" %}" class="btn-add">Добавить контерагента</a>
<table>
    <tr>
        <th>Название</th>
        <th>Операции</th>
    </tr>
    {% for contractor in contractors %}
        <tr>
            <td>{{ contractor.name }}</td>
            <td>
                <a href="{% url "shipping:update_counterparty" contractor.id %}" class="btn-update">Редактировать</a>
                <a href="{% url "shipping:delete_counterparty" contractor.id %}" class="btn-delete">Удалить</a>
            </td>
        </tr>
    {% endfor %}
</table>

<h2>Накладные</h2>
<a href="{% url "shipping:add_invoice" %}" class="btn-add">Добавить накладную</a>
<table>
    <tr>
        <th>Контрагент</th>
        <th>Операции</th>
    </tr>
    {% for invoice in shippingInvoices %}
        <tr>
            <td>{{ invoice.conterparty.name }}</td>
            <td>
                <a href="{% url "shipping:update_invoice" invoice.id %}" class="btn-update">Редактировать</a>
                <a href="{% url "shipping:delete_invoice" invoice.id %}" class="btn-delete">Удалить</a>
            </td>
        </tr>
    {% endfor %}
</table>

<h2>Выгрузки</h2>
<a href="{% url "shipping:add_shipment" %}" class="btn-add">Добавить выгрузку</a>
<table>
    <tr>
        <th>Накладная</th>
        <th>Товар</th>
        <th>Операции</th>
    </tr>
    {% for shipment in shipments %}
        <tr>
            <td>{{ shipment.shippingInvoice.id }}</td>
            <td>{{ shipment.product.name }}</td>
            <td>
                <a href="{% url "shipping:update_shipment" shipment.id %}" class="btn-update">Редактировать</a>
                <a href="{% url "shipping:delete_shipment" shipment.id %}" class="btn-delete">Удалить</a>
            </td>
        </tr>
    {% endfor %}
</table>
{% endblock content %}