products/urls.py
from django.urls import path
from .views import (
    MainView,
    ProductAdd,
    ProductUpdate,
    ProductDelete,
    UnitAdd,
    UnitUpdate,
    UnitDelete
)

app_name = 'products'

urlpatterns = [
    path('', MainView.as_view(), name='main'),

    path('add/', ProductAdd.as_view(), name='add_product'),
    path(
        'update-product/<int:pk>/',
        ProductUpdate.as_view(),
        name='update_product'
    ),
    path(
        'delete-product/<int:pk>/',
        ProductDelete.as_view(),
        name='delete_product'
    ),

    path('add-unit/', UnitAdd.as_view(), name='add_unit'),
    path('update-unit/<int:pk>/', UnitUpdate.as_view(), name='update_unit'),
    path('delete-unit/<int:pk>/', UnitDelete.as_view(), name='delete_unit'),
]

upload/urls.py
from django.urls import path

from .views import (
    main,
    ProviderAdd,
    ProviderUpdate,
    ProviderDelete,

    UploadInvoiceAdd,
    UploadInvoiceUpdate,
    UploadInvoiceDelete,

    UploadAdd,
    UploadUpdate,
    UploadDelete,
)

app_name = 'uploading'

urlpatterns = [
    path('upload-view/', main, name='main'),
    path('add-provider/', ProviderAdd.as_view(), name='add_provider'),
    path(
        'update-provider/<int:pk>/',
        ProviderUpdate.as_view(),
        name='update_provider'
    ),
    path(
        'delete-provider/<int:pk>/',
        ProviderDelete.as_view(),
        name='delete_provider'
    ),
    path('add-invoice/', UploadInvoiceAdd.as_view(), name='add_invoice'),
    path(
        'update-invoice/<int:pk>/',
        UploadInvoiceUpdate.as_view(),
        name='update_invoice'
    ),
    path(
        'delete-invoice/<int:pk>/',
        UploadInvoiceDelete.as_view(),
        name='delete_invoice'
    ),
    path('add-upload/', UploadAdd.as_view(), name='add_upload'),
    path(
        'update-upload/<int:pk>/',
        UploadUpdate.as_view(),
        name='update_upload'
    ),
    path(
        'delete-upload/<int:pk>/',
        UploadDelete.as_view(),
        name='delete_upload'
    ),
]

warehouse/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('products.urls')),
    path('shipment/', include('shipping.urls')),
    path('upload/', include('upload.urls')),
    path('admin/', admin.site.urls),
]

products/models.py
from django.db import models


class Unit(models.Model):
    name = models.CharField(
        max_length=120,
        verbose_name='Название единицы измерения'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Единица измерения'


class Product(models.Model):
    name = models.CharField(
        max_length=120,
        verbose_name='Название товара'
    )
    quantity = models.PositiveIntegerField(
        verbose_name='Количество товара'
    )
    unit = models.ForeignKey(
        "Unit",
        on_delete=models.CASCADE,
        verbose_name='Единица имземерния'
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Товары'

products/forms.py
from django import forms

from .models import Product, Unit


class ProductForm(forms.ModelForm):
    class Meta(object):
        model = Product
        exclude = ()


class UnitForm(forms.ModelForm):
    class Meta(object):
        model = Unit
        exclude = ()

products/views.py
from django.shortcuts import redirect
from django.urls import reverse_lazy

from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import TemplateView

from .models import Product, Unit
from .forms import ProductForm, UnitForm


class MainView(TemplateView):
    template_name = "products/main.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["products"] = Product.objects.all()
        context["units"] = Unit.objects.all()
        return context


class ProductAdd(CreateView):
    form_class = ProductForm
    template_name = 'form.html'
    succes_url = 'products:main'

    def form_valid(self, form):
        Product.objects.create(**form.cleaned_data)
        return redirect(self.succes_url)


class ProductUpdate(UpdateView):
    model = Product
    template_name = 'form.html'
    success_url = reverse_lazy('products:main')
    fields = ('name', 'quantity')


class ProductDelete(DeleteView):
    model = Product
    success_url = reverse_lazy('products:main')
    template_name = 'delete.html'


# Для таблицы Unit

class UnitAdd(CreateView):
    form_class = UnitForm
    template_name = 'form.html'
    succes_url = 'products:main'

    def form_valid(self, form):
        Unit.objects.create(**form.cleaned_data)
        return redirect(self.succes_url)


class UnitUpdate(UpdateView):
    model = Unit
    template_name = 'form.html'
    success_url = reverse_lazy('products:main')
    fields = ('name',)


class UnitDelete(DeleteView):
    model = Unit
    success_url = reverse_lazy('products:main')
    template_name = 'delete.html'

templates/products/main.html
{% extends "base.html" %}
{% block title %}Работа с товарами{% endblock title %}
{% block content %}
<h1>Товары</h1>
<a href="{% url "products:add_product" %}" class="btn-add">Добавить продукт</a>
<table>
    <tr>
        <th>Название</th>
        <th>Количество</th>
        <th>Единица измерения</th>
        <th>Операции</th>
    </tr>
    {% for header in products.headers %}
        {{header}}
    {% endfor %}
    {% for product in products %}
        <tr>
            <td>{{ product.name }}</td>
            <td> {{ product.quantity }} </td>
            <td> {{ product.unit.name }} </td>
            <td>
                <a href="{% url "products:update_product" product.id %}" class="btn-update">Редактировать</a>
                <a href="{% url "products:delete_product" product.id %}" class="btn-delete">Удалить</a>
            </td>
        </tr>
    {% endfor %}
</table>

<h2>Единицы измерения</h2>
<a href="{% url "products:add_unit" %}" class="btn-add">Добавить единицу измерения</a>
<table>
    <tr>
        <th>Название</th>
        <th>Операции</th>
    </tr>
    {% for unit in units %}
        <tr>
            <td>{{ unit.name }}</td>
            <td>
                <a href="{% url "products:update_unit" unit.id %}" class="btn-update">Редактировать</a>
                <a href="{% url "products:delete_unit" unit.id %}" class="btn-delete">Удалить</a>
            </td>
        </tr>
    {% endfor %}
</table>
{% endblock content %}