upload/urls.py
from django.urls import path

from .views import (
    main,
    ProviderAdd,
    ProviderUpdate,
    ProviderDelete,

    UploadInvoiceAdd,
    UploadInvoiceUpdate,
    UploadInvoiceDelete,

    UploadAdd,
    UploadUpdate,
    UploadDelete,
)

app_name = 'uploading'

urlpatterns = [
    path('upload-view/', main, name='main'),
    path('add-provider/', ProviderAdd.as_view(), name='add_provider'),
    path(
        'update-provider/<int:pk>/',
        ProviderUpdate.as_view(),
        name='update_provider'
    ),
    path(
        'delete-provider/<int:pk>/',
        ProviderDelete.as_view(),
        name='delete_provider'
    ),
    path('add-invoice/', UploadInvoiceAdd.as_view(), name='add_invoice'),
    path(
        'update-invoice/<int:pk>/',
        UploadInvoiceUpdate.as_view(),
        name='update_invoice'
    ),
    path(
        'delete-invoice/<int:pk>/',
        UploadInvoiceDelete.as_view(),
        name='delete_invoice'
    ),
    path('add-upload/', UploadAdd.as_view(), name='add_upload'),
    path(
        'update-upload/<int:pk>/',
        UploadUpdate.as_view(),
        name='update_upload'
    ),
    path(
        'delete-upload/<int:pk>/',
        UploadDelete.as_view(),
        name='delete_upload'
    ),
]

warehouse/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('products.urls')),
    path('shipment/', include('shipping.urls')),
    path('upload/', include('upload.urls')),
    path('admin/', admin.site.urls),
]

upload/models.py
from django.db import models


class Provider(models.Model):
    """Модель таблицы Поставщик"""

    name = models.CharField(
        max_length=50,
        verbose_name='Название фирмы',
    )

    class Meta:
        verbose_name = 'Поставщик'
        verbose_name_plural = 'Поставщики'
    
    def __str__(self):
        return self.name


class UploadInvoice(models.Model):
    """Модель таблицы Накладная"""

    provider = models.ForeignKey(
        "Provider",
        verbose_name=('Поставщик'),
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = 'Приходная накладная'
        verbose_name_plural = 'Приходные накладные'
    
    def __str__(self):
        return self.id


class Upload(models.Model):
    """Модель таблицы Выгрузка"""

    invoice = models.ForeignKey(
        "UploadInvoice",
        verbose_name=('Накладная'),
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        "products.Product",
        verbose_name=('Товар'),
        on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = 'Выгрузка'
        verbose_name_plural = 'Выгрузки'
    
    def __str__(self):
        return f'Выгрузка №{self.id} Накладная №{self.invoice.id}'

upload/forms.py
from django import forms

from .models import Provider, UploadInvoice, Upload


class ProviderForm(forms.ModelForm):
    class Meta:
        model = Provider
        exclude = ()


class UploadInvoiceForm(forms.ModelForm):
    class Meta:
        model = UploadInvoice
        exclude = ()


class UploadForm(forms.ModelForm):
    class Meta:
        model = Upload
        exclude = ()

upload/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy

from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .models import Provider, UploadInvoice, Upload
from .forms import ProviderForm, UploadInvoiceForm, UploadForm


def main(request):
    template_name = 'upload/main.html'
    context = {
        'providers': Provider.objects.all(),
        'invocies': UploadInvoice.objects.all(),
        'uploads': Upload.objects.all(),
    }
    return render(request, template_name, context)


class ProviderAdd(CreateView):
    form_class = ProviderForm
    template_name = 'form.html'
    succes_url = 'uploading:upload_view'

    def form_valid(self, form):
        Provider.objects.create(**form.cleaned_data)
        return redirect(self.succes_url)


class ProviderUpdate(UpdateView):
    model = Provider
    template_name = 'form.html'
    success_url = reverse_lazy('uploading:upload_view')
    fields = ('name',)


class ProviderDelete(DeleteView):
    model = Provider
    success_url = reverse_lazy('uploading:upload_view')
    template_name = 'delete.html'


class UploadInvoiceAdd(CreateView):
    form_class = UploadInvoiceForm
    template_name = 'form.html'
    succes_url = 'uploading:upload_view'

    def form_valid(self, form):
        UploadInvoice.objects.create(**form.cleaned_data)
        return redirect(self.succes_url)


class UploadInvoiceUpdate(UpdateView):
    model = UploadInvoice
    template_name = 'form.html'
    success_url = reverse_lazy('uploading:upload_view')
    fields = ('provider',)


class UploadInvoiceDelete(DeleteView):
    model = UploadInvoice
    success_url = reverse_lazy('uploading:upload_view')
    template_name = 'delete.html'


class UploadAdd(CreateView):
    form_class = UploadForm
    template_name = 'form.html'
    succes_url = 'uploading:upload_view'

    def form_valid(self, form):
        Upload.objects.create(**form.cleaned_data)
        return redirect(self.succes_url)


class UploadUpdate(UpdateView):
    model = Upload
    template_name = 'form.html'
    success_url = reverse_lazy('uploading:upload_view')
    fields = ('invoice', 'product')


class UploadDelete(DeleteView):
    model = Upload
    success_url = reverse_lazy('uploading:upload_view')
    template_name = 'delete.html'

templates/upload/main.html
{% extends "base.html" %}
{% block title %}Работа с приходами{% endblock title %}
{% block content %}

<h1>Приходы</h1>

<h3>Поставщики</h3>
<a href="{% url "uploading:add_provider" %}" class="btn-add">Добавить контерагента</a>
<table>
    <tr>
        <th>Название</th>
        <th>Операции</th>
    </tr>
    {% for provider in providers %}
        <tr>
            <td>{{ provider.name }}</td>
            <td>
                <a href="{% url "uploading:update_provider" provider.id %}" class="btn-update">Редактировать</a>
                <a href="{% url "uploading:delete_provider" provider.id %}" class="btn-delete">Удалить</a>
            </td>
        </tr>
    {% endfor %}
    
</table>

<h3>Накладные</h3>
<a href="{% url "uploading:add_invoice" %}" class="btn-add">Добавить накладную</a>
<table>
    <tr>
        <th>Номер накладной</th>
        <th>Поставщик</th>
        <th>Операции</th>
    </tr>
    {% for invocie in invocies %}
        <tr>
            <td>{{ invocie.id }}</td>
            <td>{{ invocie.provider.name }}</td>
            <td>
                <a href="{% url "uploading:update_invoice" invocie.id %}" class="btn-update">Редактировать</a>
                <a href="{% url "uploading:delete_invoice" invocie.id %}" class="btn-delete">Удалить</a>
            </td>
        </tr>
    {% endfor %}
    
</table>


<h3>Приходы</h3>
<a href="{% url "uploading:add_upload" %}" class="btn-add">Добавить накладную</a>
<table>
    <tr>
        <th>Номер накладной</th>
        <th>Товар</th>
        <th>Операции</th>
    </tr>
    {% for upload in uploads %}
        <tr>
            <td>{{ upload.invoice.id }}</td>
            <td>{{ upload.product.name }}</td>
            <td>
                <a href="{% url "uploading:update_upload" upload.id %}" class="btn-update">Редактировать</a>
                <a href="{% url "uploading:delete_upload" upload.id %}" class="btn-delete">Удалить</a>
            </td>
        </tr>
    {% endfor %}
    
</table>


{% endblock content %}