products/urls.py
from django.urls import path
from .views import (
    MainView,
    ProductAdd,
    ProductUpdate,
    ProductDelete,
    UnitAdd,
    UnitUpdate,
    UnitDelete
)

app_name = 'products'

urlpatterns = [
    path('', MainView.as_view(), name='main'),

    path('add/', ProductAdd.as_view(), name='add_product'),
    path(
        'update-product/<int:pk>/',
        ProductUpdate.as_view(),
        name='update_product'
    ),
    path(
        'delete-product/<int:pk>/',
        ProductDelete.as_view(),
        name='delete_product'
    ),

    path('add-unit/', UnitAdd.as_view(), name='add_unit'),
    path('update-unit/<int:pk>/', UnitUpdate.as_view(), name='update_unit'),
    path('delete-unit/<int:pk>/', UnitDelete.as_view(), name='delete_unit'),
]

shipping/urls.py
from django.urls import path

from .views import (
    MainView,
    СounterpartyAdd,
    СounterpartyUpdate,
    СounterpartyDelete,
    ShippingInvoiceAdd,
    ShippingInvoiceUpdate,
    ShippingInvoiceDelete,
    ShipmentAdd,
    ShipmentUpdate,
    ShipmentDelete,
)

app_name = 'shipping'

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path(
        'add-counterparty/',
        СounterpartyAdd.as_view(),
        name='add_counterparty'
    ),
    path(
        'udate-counterparty/<int:pk>/',
        СounterpartyUpdate.as_view(),
        name='update_counterparty'
    ),
    path(
        'delete_counterparty/<int:pk>/',
        СounterpartyDelete.as_view(),
        name='delete_counterparty'
    ),
    path('add-invoice/', ShippingInvoiceAdd.as_view(), name='add_invoice'),
    path(
        'udate-invoice/<int:pk>/',
        ShippingInvoiceUpdate.as_view(),
        name='update_invoice'
    ),
    path(
        'delete_invoice/<int:pk>/',
        ShippingInvoiceDelete.as_view(),
        name='delete_invoice'
    ),
    path('add-shipment/', ShipmentAdd.as_view(), name='add_shipment'),
    path(
        'udate-shipment/<int:pk>/',
        ShipmentUpdate.as_view(),
        name='update_shipment'
    ),
    path(
        'delete_shipment/<int:pk>/',
        ShipmentDelete.as_view(),
        name='delete_shipment'
    ),
]

upload/urls.py
from django.urls import path

from .views import (
    main,
    ProviderAdd,
    ProviderUpdate,
    ProviderDelete,

    UploadInvoiceAdd,
    UploadInvoiceUpdate,
    UploadInvoiceDelete,

    UploadAdd,
    UploadUpdate,
    UploadDelete,
)

app_name = 'uploading'

urlpatterns = [
    path('upload-view/', main, name='main'),
    path('add-provider/', ProviderAdd.as_view(), name='add_provider'),
    path(
        'update-provider/<int:pk>/',
        ProviderUpdate.as_view(),
        name='update_provider'
    ),
    path(
        'delete-provider/<int:pk>/',
        ProviderDelete.as_view(),
        name='delete_provider'
    ),
    path('add-invoice/', UploadInvoiceAdd.as_view(), name='add_invoice'),
    path(
        'update-invoice/<int:pk>/',
        UploadInvoiceUpdate.as_view(),
        name='update_invoice'
    ),
    path(
        'delete-invoice/<int:pk>/',
        UploadInvoiceDelete.as_view(),
        name='delete_invoice'
    ),
    path('add-upload/', UploadAdd.as_view(), name='add_upload'),
    path(
        'update-upload/<int:pk>/',
        UploadUpdate.as_view(),
        name='update_upload'
    ),
    path(
        'delete-upload/<int:pk>/',
        UploadDelete.as_view(),
        name='delete_upload'
    ),
]

warehouse/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('products.urls')),
    path('shipment/', include('shipping.urls')),
    path('upload/', include('upload.urls')),
    path('admin/', admin.site.urls),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport">
    <link rel="stylesheet" href="{% static "css/base.css" %}">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    <nav>
        <a href="{% url "products:main" %}">Главная</a>
        <a href="{% url "shipping:main" %}">Расходы</a>
        <a href="{% url "uploading:main" %}">Приходы</a>
    </nav>
    {% block content %}{% endblock content %}

</body>
</html>

templates/delete.html
<h3>Ты точно хочешь удалить "{{product.name}}"</h3>
<form method='post'>{% csrf_token %}
    <button type="submit">Удалить</button>
</form>

templates/form.html
{% extends "base.html" %}
{% block content %}
<br>
<br>
<br>
<form method="post"> {% csrf_token %}
    {% comment %} {% for input in form %}
         <br>
        {{ input }} <br> <br>
    {% endfor %} {% endcomment %}
    {{form}}
    <button type="submit">Сохранить</button>
</form>
{% endblock content %}